### ISSUE TITLE
Get rid of src/tests/ subdirectory, reorganize source hierarchy

### ISSUE THREAD

**Issue by rye** [rye/rust-netaddr2#38]
One does not need to have such a directory. There is already a mechanism for integration tests; it is far better to put tests in the modules that they are testing.

- [x] `src/tests/netaddr/from/ipaddr.rs` (#39, #48)
- [x] `src/tests/netaddr/merge.rs` (#44)
- [x] `src/tests/netaddr/parse.rs` (#51)
- [x] `src/tests/netaddr/from.rs` (#39)
- [x] `src/tests/netaddr/broadcast.rs` (#45)
- [x] `src/tests/netaddr/cmp.rs` (#53)
- [x] `src/tests/netaddr/contains.rs` (#54)
- [x] `src/tests/util.rs` (#50)
- [x] `src/tests/util/gen_v4_mask.rs` (#50)
- [x] `src/tests/util/gen_v6_mask.rs` (#50)
- [ ] `src/tests/netaddr.rs` (#55)
- [ ] `src/tests/netaddr_error.rs` (#55)
